/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg277Project;

import javax.swing.JInternalFrame;

/**
 *
 * @author ianbw
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusBar = new javax.swing.JLabel();
        mydesktop = new javax.swing.JDesktopPane();
        jComboBox2 = new javax.swing.JComboBox<>();
        Details = new javax.swing.JButton();
        Simple = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Rename = new javax.swing.JMenuItem();
        Copy = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenuItem();
        Run = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Tree = new javax.swing.JMenu();
        Expand = new javax.swing.JMenuItem();
        Collapse = new javax.swing.JMenuItem();
        Window = new javax.swing.JMenu();
        New = new javax.swing.JMenuItem();
        Cascade = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        Help_item = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        statusBar.setText("jLabel1");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Details.setText("Details");
        Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsActionPerformed(evt);
            }
        });

        Simple.setText("Simple");

        mydesktop.setLayer(jComboBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mydesktop.setLayer(Details, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mydesktop.setLayer(Simple, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mydesktopLayout = new javax.swing.GroupLayout(mydesktop);
        mydesktop.setLayout(mydesktopLayout);
        mydesktopLayout.setHorizontalGroup(
            mydesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mydesktopLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Details)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Simple)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mydesktopLayout.setVerticalGroup(
            mydesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mydesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mydesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Details)
                    .addComponent(Simple))
                .addContainerGap(421, Short.MAX_VALUE))
        );

        File.setText("File");

        Rename.setText("Rename");
        File.add(Rename);

        Copy.setText("Copy");
        File.add(Copy);

        Delete.setText("Delete");
        File.add(Delete);

        Run.setText("Run");
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });
        File.add(Run);

        Exit.setText("Exit");
        File.add(Exit);

        jMenuBar1.add(File);

        Tree.setText("Tree");
        Tree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreeActionPerformed(evt);
            }
        });

        Expand.setText("Expand");
        Tree.add(Expand);

        Collapse.setText("Collapse");
        Collapse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollapseActionPerformed(evt);
            }
        });
        Tree.add(Collapse);

        jMenuBar1.add(Tree);

        Window.setText("Window");

        New.setText("New");
        New.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewMouseClicked(evt);
            }
        });
        Window.add(New);

        Cascade.setText("Cascade");
        Window.add(Cascade);

        jMenuBar1.add(Window);

        Help.setText("Help");

        Help_item.setText("Help");
        Help.add(Help_item);

        About.setText("About");
        Help.add(About);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(536, 536, 536))
            .addComponent(mydesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mydesktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DetailsActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        
    }                                       
    private void TreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DetailsActionPerformed

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RunActionPerformed

    private void CollapseActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollapseActionPerformed
        // TODO add your handling code here:
        final InternalFrame IF=new InternalFrame();
        mydesktop.add(IF);
        IF.setVisible(true);
    }//GEN-LAST:event_CollapseActionPerformed

    private void NewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuItem Cascade;
    private javax.swing.JMenuItem Collapse;
    private javax.swing.JMenuItem Copy;
    private javax.swing.JMenuItem Delete;
    private javax.swing.JButton Details;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem Expand;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem Help_item;
    private javax.swing.JMenuItem New;
    private javax.swing.JMenuItem Rename;
    private javax.swing.JMenuItem Run;
    private javax.swing.JButton Simple;
    private javax.swing.JMenu Tree;
    private javax.swing.JMenu Window;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane mydesktop;
    private javax.swing.JLabel statusBar;
    // End of variables declaration//GEN-END:variables
}
